name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cached download
        id: cached-download
        uses: actions/cache@v3
        with:
          path: WowzaStreamingEngine-4.8.15+3-linux-x64-installer.run
          key: WowzaStreamingEngine-4.8.15+3-linux-x64-installer.run
      - name: Download Wowza Streaming Engine installer
        if: steps.cached-download.outputs.cache-hit != 'true'
        run: |
          curl -L -O "https://www.wowza.com/downloads/WowzaStreamingEngine-4-8-15+3/WowzaStreamingEngine-4.8.15+3-linux-x64-installer.run"
      - name: Set up JDK 9
        uses: actions/setup-java@v3
        with:
          java-version: '9'
          distribution: 'adopt'
      - run: sudo apt install -y expect
      - name: Prepare installer
        run: |
          chmod +x WowzaStreamingEngine-4.8.15+3-linux-x64-installer.run
      - name: Install Wowza Streaming Engine
        run: |
          sudo .github/workflows/install.exp ${{ secrets.WOWZA_LICENSE_KEY }}
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v3
        with:
          name: wowza-plugin-switchtube
          path: ./dist/*.jar
          retention-days: 3
